twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        config: '@App\Manager\SettingsManager'
        booker: '@App\Storage\BookingSessionStorage'
        roomService: '@App\Service\RoomService'

when@test:
    twig:
        strict_variables: true


