vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        settings:
            uri_prefix: '%app.path.settings%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.settings%'
        promotion:
            uri_prefix: '%app.path.promotion%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.promotion%'
        user:
            uri_prefix: '%app.path.user%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.user%'

